version: '3'

services:
    # db:
    #   image: "postgres"
    #   ports:
    #     - "5433:5432"
    #   environment:
    #       POSTGRES_DB: postgres
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    redis:
      image: redis
      hostname: redis

    zoo:
      image: zookeeper:3.4.9
      hostname: zoo
      ports:
        - "2181:2181"
      environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo:2888:3888
      volumes:
        - ./zk-single-kafka-single/zoo/data:/data
        - ./zk-single-kafka-single/zoo/datalog:/datalog
 
    kafka:
      image: confluentinc/cp-kafka:5.5.3
      hostname: kafka
      container_name: kafka
      ports:
        - "9092:9092"
        - "19092:19092"
      environment:
        KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092
        KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
        KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
        KAFKA_BROKER_ID: 1
        KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      volumes:
        - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
      depends_on:
        - zoo

    gateway:
      build: ./Gateway
      hostname: gateway
      ports:
        - "8082:8080"
      depends_on:
        - product
        - order
    
    order:
      build: ./Order
      # image: order
      hostname: order
      ports:
        - "8080:8080"
      depends_on:
        - db
        - kafka

    product:
      build: ./Product
      # image: product
      hostname: product
      ports:
        - "8081:8080"
      depends_on:
        - db
        - kafka

    
