cloud:
  aws:
    region:
      static: us-west-2
      auto: false
    credentials:
      access-key: AKIA2LPO5M2FEENI6PXV
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error