export const ORDER_HISTORY_ADMIN_REQUEST = 'ORDER_HISTORY_ADMIN_REQUEST';
export const ORDER_HISTORY_ADMIN_SUCCESS = 'ORDER_HISTORY_ADMIN_SUCCESS';
export const ORDER_HISTORY_ADMIN_FAIL = 'ORDER_HISTORY_ADMIN_FAIL';

export const USER_LIST_ADMIN_REQUEST = 'USER_LIST_ADMIN_REQUEST';
export const USER_LIST_ADMIN_SUCCESS = 'USER_LIST_ADMIN_SUCCESS';
export const USER_LIST_ADMIN_FAIL = 'USER_LIST_ADMIN_FAIL';

export const PRODUCT_LIST_ADMIN_REQUEST = 'PRODUCT_LIST_ADMIN_REQUEST';
export const PRODUCT_LIST_ADMIN_SUCCESS = 'PRODUCT_LIST_ADMIN_SUCCESS';
export const PRODUCT_LIST_ADMIN_FAIL = 'PRODUCT_LIST_ADMIN_FAIL';